### ISSUE TITLE
Can't run mailhog container on M1 Mac

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/starchart#158]
The new Mailhog Docker container won't run on my M1 Mac.  It looks like [there's another image](https://github.com/mailhog/MailHog/issues/359#issuecomment-1107160980) we can use that does support it.

This worked for me:

```yml
  mailhog:
    # https://github.com/mailhog/MailHog/issues/359#issuecomment-1107160980
    image: jcalonso/mailhog
    container_name: mailhog
    ports:
      - 8025:8025 # MailHog interface
      - 1025:1025 # SMTP server
```
